-- Initial PCS Commons task catalog.
-- Open tasks are non-exclusive. Approval/invite tasks do not reserve while pending.
-- Synthetic CAL-* fixtures exist only to demonstrate skill and must not be treated as unpaid production work.

INSERT OR IGNORE INTO tasks
(id,title,summary,min_level,claim_mode,required_skill,calibrates_skill,expected_hours,review_sla_business_days,checkpoint_hours,reservation_hours,max_active_per_user,status,compensation_type,compensation_label,funding_status,created_at,updated_at)
VALUES
('AS-001','Reproduce a bounded trace checker','Follow a deterministic trace-checking walkthrough and independently confirm the declared forbidden-action count.',0,'open',NULL,NULL,1,2,NULL,NULL,2,'open','volunteer','Volunteer','open',datetime('now'),datetime('now')),
('AS-002','Annotate agent actions against a policy rubric','Classify a small set of synthetic agent actions as allowed, forbidden, or ambiguous under a supplied rubric.',0,'open',NULL,NULL,2,2,NULL,NULL,2,'open','volunteer','Volunteer','open',datetime('now'),datetime('now')),
('AS-003','Audit claims against evidence in a safety report','Check whether a bounded safety conclusion is stronger than the evidence actually shown.',1,'open','research',NULL,2,2,NULL,NULL,2,'open','volunteer','Volunteer','open',datetime('now'),datetime('now')),
('OPS-001','Test whether a new contributor can understand one task unaided','Use the task page without founder assistance and record every term, instruction, or acceptance condition that is unclear.',1,'open',NULL,NULL,1,2,NULL,NULL,2,'open','volunteer','Volunteer','open',datetime('now'),datetime('now')),
('AS-004','Write adversarial tool-permission cases','Create cases intended to bypass a declared tool authorization policy without changing the policy itself.',2,'approval','python',NULL,3,2,24,72,1,'open','bounty','$150 proposed','planned',datetime('now'),datetime('now')),
('AS-005','Implement single-use authorization invariant checker','Implement a fail-closed checker that rejects reuse of a consumed authorization token.',2,'approval','python',NULL,4,2,24,72,1,'open','bounty','$250 proposed','planned',datetime('now'),datetime('now')),
('AS-006','Independent evaluator-binding review','Review whether model, evaluator, dataset, configuration, and result commitments are bound strongly enough to prevent substitution.',3,'approval','ml',NULL,5,2,24,72,1,'open','bounty','$400 proposed','planned',datetime('now'),datetime('now')),
('AS-007','Decompose a bounded agent-safety claim','Turn a high-level bounded safety claim into explicit formal, computational, empirical, and OPEN leaves.',3,'approval','research',NULL,5,2,24,72,1,'open','bounty','$350 proposed','planned',datetime('now'),datetime('now')),
('AS-008','Review a contributor-built assurance graph','Independently challenge a completed obligation graph and identify unsupported leaves, missing dependencies, or inappropriate closure.',4,'invite','review',NULL,3,2,24,72,1,'open','review','$300 proposed','planned',datetime('now'),datetime('now')),
('AS-009','Formalize a trace-invariant preservation lemma','Formalize a bounded transition invariant in Lean without introducing proof escapes.',5,'invite','lean',NULL,8,2,24,72,1,'open','contract','$1,200 proposed','planned',datetime('now'),datetime('now')),
('AS-010','Red-team contributor non-authority','Attempt to manufacture a false accepted root through colluding contributors, stale evidence, wrong-leaf evidence, or ordering attacks.',5,'invite','security',NULL,8,2,24,72,1,'open','contract','$1,500 proposed','planned',datetime('now'),datetime('now')),
('SCI-001','Map a computational-biology claim into bounded obligations','Propose a precise computational-biology assurance case scoped to committed artifacts rather than external biology.',3,'approval','biology',NULL,5,2,24,72,1,'open','bounty','$350 proposed','planned',datetime('now'),datetime('now')),

('CAL-PY-001','Python checker calibration','Inspect a synthetic fail-open checker, identify the defect, repair it, and add a regression test. The fixture is deliberately non-production and exists only to demonstrate skill.',0,'open',NULL,'python',2,2,NULL,NULL,2,'open','volunteer','Unpaid synthetic calibration','calibration',datetime('now'),datetime('now')),
('CAL-LEAN-001','Lean proof calibration','Work on a synthetic Lean theorem package: identify an invalid or under-scoped theorem/proof boundary, repair the formal statement or proof, and explain the assumptions. The fixture is not production PCS research.',0,'open',NULL,'lean',2,2,NULL,NULL,2,'open','volunteer','Unpaid synthetic calibration','calibration',datetime('now'),datetime('now')),
('CAL-SEC-001','Security threat-model calibration','Analyze a synthetic authorization workflow, find a concrete bypass or explain why proposed attacks fail, and write a minimal regression case. This is a non-production fixture.',0,'open',NULL,'security',2,2,NULL,NULL,2,'open','volunteer','Unpaid synthetic calibration','calibration',datetime('now'),datetime('now')),
('CAL-ML-001','ML evaluation calibration','Audit a synthetic model-evaluation package for leakage, evaluator/data binding, or metric interpretation errors and propose a reproducible correction.',0,'open',NULL,'ml',2,2,NULL,NULL,2,'open','volunteer','Unpaid synthetic calibration','calibration',datetime('now'),datetime('now')),
('CAL-RES-001','Research evidence calibration','Evaluate a synthetic safety claim against a supplied evidence packet, distinguish supported from overstated conclusions, and identify remaining OPEN assumptions.',0,'open',NULL,'research',1,2,NULL,NULL,2,'open','volunteer','Unpaid synthetic calibration','calibration',datetime('now'),datetime('now')),
('CAL-BIO-001','Computational biology calibration','Audit a synthetic sequence/score claim, check index and threshold semantics, and separate statements about committed artifacts from statements about an external biological object.',0,'open',NULL,'biology',2,2,NULL,NULL,2,'open','volunteer','Unpaid synthetic calibration','calibration',datetime('now'),datetime('now')),
('CAL-REV-001','Independent review calibration','Review a synthetic assurance graph containing subtle missing dependencies and over-closure. Produce a reasoned accept/reject/OPEN decision per node.',0,'open',NULL,'review',2,2,NULL,NULL,2,'open','volunteer','Unpaid synthetic calibration','calibration',datetime('now'),datetime('now'));
