// Compare actual independent implementations, including entire replay receipts.
import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
import {canonical,strictParse} from '../public/omega-core.mjs';import {checkConditional,conditionalFromText,verifyConditional} from '../public/conditional-core.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),args=process.argv.slice(2),core=args[args.indexOf('--core')+1];if(!args.includes('--core')||!core)throw Error('Supply the independent PCS checkout with --core');
const vectors=[['A AND B','A OR B',''],['TRUE','FALSE',''],['A OR B AND C','A -> B -> C','A\u2028B'],['A\u0085AND B','A AND B','A\u001cB'],['A\ufeff','A',''],['A','B','\ufeffA'],['A B','A',''],['A AND','TRUE','']];
const code=`import hashlib,json,sys\nfrom pathlib import Path\nsys.path.insert(0,sys.argv[1]);sys.path.insert(0,sys.argv[1]+'/scripts')\nfrom benchmark_conditional import cases\nfrom pcs.experimental.conditional import check,from_text\nrows=[{'id':c['id'],'task':c['task'],'receipt':check(c['task'])} for c in cases()]\nparsed=[]\nfor text in json.loads(sys.argv[2]):\n try:parsed.append({'valid':True,'task':from_text(*text)})\n except ValueError:parsed.append({'valid':False,'task':None})\nprint(json.dumps({'source_sha256':hashlib.sha256((Path(sys.argv[1])/'pcs/experimental/conditional.py').read_bytes()).hexdigest(),'rows':rows,'parser':parsed}))`;
const child=spawnSync('python3',['-c',code,path.resolve(core),JSON.stringify(vectors)],{encoding:'utf8',maxBuffer:8*1024*1024});if(child.status!==0)throw Error(child.stderr||'Independent Python checker failed');const data=JSON.parse(child.stdout),published=JSON.parse(fs.readFileSync(path.join(root,'public/reasoning/measurements-v1.json'),'utf8'));if(data.source_sha256!==published.python_source_sha256)throw Error('Published symbolic source pin does not match independent core');
for(const row of data.rows){const r=await checkConditional(row.task);if(canonical(r)!==canonical(row.receipt))throw Error('Conditional Python/browser receipt mismatch: '+row.id);await verifyConditional(r);}
for(const [i,text] of vectors.entries()){let actual;try{actual={valid:true,task:conditionalFromText(...text)};}catch{actual={valid:false,task:null};}if(canonical(actual)!==canonical(data.parser[i]))throw Error('Conditional parser parity mismatch: '+i);}
console.log(JSON.stringify({cases:data.rows.length,entire_receipts_match:true,parser_vectors:vectors.length,python_source_sha256:data.source_sha256,paid_services:false}));
